# Generated by Django 5.0.7 on 2025-05-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_purchasetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetransaction',
            name='product_type',
            field=models.CharField(choices=[('ExamPin', 'ExamPin'), ('DataCoupon', 'DataCoupon')], max_length=20),
        ),
    ]
