# Generated by Django 5.0.7 on 2025-05-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_purchasetransaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampin',
            name='name',
            field=models.CharField(choices=[('waec_card', 'WAEC Scratch Card'), ('neco_token', 'NECO TOKEN'), ('nabteb_card', 'NABTEB Scratch Card'), ('waec_verification', 'WAEC Verification Pin'), ('nbais_card', 'NBAIS Scratch Card'), ('waec_gce', 'WAEC GCE Registration Card'), ('neco_verification', 'NECO e-VERIFICATION PIN'), ('examinify_token', 'EXAMINIFY BIOMETRIC TOKEN')], max_length=50),
        ),
    ]
