# Generated by Django 5.0.7 on 2025-05-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_exampin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampin',
            name='name',
            field=models.CharField(choices=[('WAEC Scratch Card', 'WAEC Scratch Card'), ('NECO TOKEN', 'NECO TOKEN'), ('NABTEB Scratch Card', 'NABTEB Scratch Card'), ('WAEC Verification Pin', 'WAEC Verification Pin'), ('NBAIS Scratch Card', 'NBAIS Scratch Card'), ('WAEC GCE Registration Card', 'WAEC GCE Registration Card'), ('NECO e-VERIFICATION PIN', 'NECO e-VERIFICATION PIN'), ('EXAMINIFY BIOMETRIC TOKEN', 'EXAMINIFY BIOMETRIC TOKEN')], max_length=50),
        ),
    ]
