# Generated by Django 5.0.7 on 2025-05-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_exampin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='product',
            field=models.CharField(default='EXAM_PIN', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
