# Generated by Django 5.0.7 on 2025-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_purchasetransaction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampin',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
