# Generated by Django 5.0.7 on 2025-05-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_exampin_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetransaction',
            name='description',
            field=models.TextField(blank=True, default='No description available'),
            preserve_default=False,
        ),
    ]
