# Generated by Django 5.0.7 on 2025-05-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monnify', '0003_alter_virtualaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
