# Generated by Django 5.0.7 on 2025-05-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastquestions', '0002_purchasetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='successful', max_length=20),
        ),
    ]
