# Generated by Django 5.0.7 on 2025-05-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastquestions', '0003_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_reference',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='paid', max_length=10),
        ),
    ]
