# Generated by Django 5.0.7 on 2025-05-28 00:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastquestions', '0004_alter_purchase_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
